- name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:      ${{ secrets.FTP_SERVER }}
          username:    ${{ secrets.FTP_USERNAME }}
          password:    ${{ secrets.FTP_PASSWORD }}
          server-dir:  /home/evolution32/public_html/teste/
          local-dir:   ./
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/dist/**
            .github/**
            README.md
            fix-permissions.php
            diff.txt
            fix_price.js
            fix_sync.js
            patch.js
            sync.js
            screen.png
            package.json
            package-lock.json
            vite.config.js
